### ISSUE TITLE
Smartphone app - Physician logging

### ISSUE THREAD

**Issue by vaibhav-clearsense** [ClearsenseData/personicle-rails#100]
Screens for physician questionnaire logging

![image](https://user-images.githubusercontent.com/97196207/192335133-8dab70c2-4fdc-4d95-a332-6448309ab345.png)

**Comment by vaibhav-clearsense** [comment]
@tirth-clearsense 
Unable to log responses to multiple questions

**Comment by vaibhav-clearsense** [comment]
Re: Need to verify if the responses are being logged from the app

The data is not being logged in the db. Probably an issue with the custom consumer, need to check logs there and see if it is receiving and sending data packets to the database

**Comment by patel-tirth** [comment]
fixed by [commit](https://github.com/vaibhav-clearsense/personicle-react-application/commit/910451c82d13d5fc13437a7ab87b92fae7ea8564)

**Comment by vaibhav-clearsense** [comment]
need to test; will close the issue after that

**Comment by vaibhav-clearsense** [comment]
Error while logging image response (@vaibhav-clearsense)

**Comment by vaibhav-clearsense** [comment]
@vaibhav-clearsense will pull the latest version of the code and test it

**Comment by vaibhav-clearsense** [comment]
For image logging:

- Show a zoomed out (smaller) view of the image being uploaded

**Comment by vaibhav-clearsense** [comment]
Use UTC timestamp when logging from the react app.

**Comment by tirth-clearsense** [comment]
fixed by [commit](https://github.com/vaibhav-clearsense/personicle-react-application/commit/d11d50314600dd5facee2c2cf232cf93caa3de78)
