### ISSUE TITLE
Smartphone app - Survey response visualization

### ISSUE THREAD

**Issue by vaibhav-clearsense** [ClearsenseData/personicle-rails#102]
![image](https://user-images.githubusercontent.com/97196207/193622904-c18e00bd-a8e6-4e2d-a93c-05dbfaafcb8b.png)

**Comment by vaibhav-clearsense** [comment]
1. Image response visualization need to be implemented

**Comment by vaibhav-clearsense** [comment]
A Gallery View showing al images in a temporal order (latest images at the top)
selecting an image takes us to the zoomed-in view, in which we show the time stamp of the image

**Comment by patel-tirth** [comment]
<img width="376" alt="Screen Shot 2022-11-15 at 3 46 54 PM" src="https://user-images.githubusercontent.com/46164826/202048846-23cf6eda-9eb2-4e62-91cd-8bf0705681cf.png">

**Comment by vaibhav-clearsense** [comment]
https://www.npmjs.com/package/react-native-grid-image-viewer

this may be a viable solution for image grid layout

**Comment by vaibhav-clearsense** [comment]
For line chart: Increase the range of the y-axis for the chart to [min - 10%(max-min), max + 10%(max-min)]

**Comment by tirth-patel17** [comment]
fixed by [commit](https://github.com/vaibhav-clearsense/personicle-react-application/commit/5118a01d5c6319a0c7e33b2d2fecdb77ade10383)

**Comment by tirth-clearsense** [comment]
fixed by [commit](https://github.com/vaibhav-clearsense/personicle-react-application/commit/5118a01d5c6319a0c7e33b2d2fecdb77ade10383)

**Comment by vaibhav-clearsense** [comment]
![Image](https://user-images.githubusercontent.com/97196207/206233756-64d8cf02-c592-40b1-aa62-7bf343c37bd8.png)

Invalid date being shown, need to look into it

**Comment by vaibhav-clearsense** [comment]
1. Change the color of the bar chart. Use a color not present in the pie chart
2. Add a title above the bar chart

**Comment by vaibhav-clearsense** [comment]
5. Add image timestamp to image visualization

**Comment by vaibhav-clearsense** [comment]
![Image](https://user-images.githubusercontent.com/97196207/213805981-9237c133-cb34-48f5-81d4-8d039935519c.png)

**Comment by tirth-clearsense** [comment]
fixed by [commit](https://github.com/vaibhav-clearsense/personicle-react-application/commit/f9539d67476948a72578c00a35b5aa33e37eb937). We try to get the response type from  the object of type {"question-id: : ["null", "numeric", "numeric"]}. To determine the response type of a particular question-id, only the first value from the array was checked which incorrectly showed the above message when the value was null.
