### ISSUE TITLE
Update event feature - events data table

### ISSUE THREAD

**Issue by vaibhav-clearsense** [ClearsenseData/personicle-rails#103]
Allow users to modify their events from the data table.

- [x] Editable input elements in the table (dates and text input)
- [x] Maintain the list of selected events in the browser (javascript)
- [x] Rails API endpoint for updating the event (Delete + Add event API calls needed)

**Comment by vaibhav-clearsense** [comment]
@zara-clearsense please create a pull request to close this issue

**Comment by vaibhav-clearsense** [comment]
Issue with the pre-existing events where start time > end time, 
- can't delete such events in one click
- Date out of bound message shows up only for start time, need to test what happens when start time is fixed.

**Comment by vaibhav-clearsense** [comment]
- can't delete such events in one click

This needs to be handled in the rails controller itself so that such events are not shown on the dashboard. This should also resolve the out-of-bound message for dates. But we should still test that the out-of-bound message works for both fields.

**Comment by vaibhav-clearsense** [comment]
page content spilling behind the side nav bar; need to fix this

**Comment by vaibhav-clearsense** [comment]
create a pull request for the current version of the code

**Comment by zara-clearsense** [comment]
https://github.com/zara-clearsense/personicle-rails/tree/data-table-revisit
