### ISSUE TITLE
Personicle web dashboard: Analysis scatterplot: Anomaly removal

### ISSUE THREAD

**Issue by vaibhav-clearsense** [ClearsenseData/personicle-rails#121]
Find std. deviation for X and Y axis in the scatter plot data.
Filter the data based using the range [mean - 3*std.dev, mean + 3*std.dev]

**Comment by vaibhav-clearsense** [comment]
@zara-clearsense Add the details of the anomaly removal methodology, then you can close the issue

**Comment by zara-clearsense** [comment]
Approach:

- Created a function for calculating percentile(values,percentile) which gives values for x and y based on a given percentile. The function can be used to find the upper and lower bounds for x and y. We then remove x and y values in the x and y arrays that are outside of these bounds for the anomaly removal.
