### ISSUE TITLE
Image + data caching on-device

### ISSUE THREAD

**Issue by vaibhav-clearsense** [ClearsenseData/personicle-rails#123]
Solve this in stages:

![Image](https://user-images.githubusercontent.com/97196207/204314135-387efa32-e8eb-4f8e-994d-71107b5d3d97.png)

**Comment by tirth-clearsense** [comment]
[React query]((https://tanstack.com/query/v4/?from=reactQueryV3&original=https://react-query-v3.tanstack.com/) can be used to achieve this. On component load, get data from cache if available. Re fetch API after x amount of time.
If the data is changed from the app itself (example user updates profile data), invalidate data in current cache and update cache with changes from user along with making api call to update the changes on server. useMutation hook can be used to achieve this.  User will see their update immediately. useQuery hook will be triggered whenever the cache is updated. useQuery will make the api call in the background to fetch new changes.

**Comment by tirth-clearsense** [comment]
Update: The above functionality is tested with user data.

**Comment by vaibhav-clearsense** [comment]
Current status:
Profile information is cached on the device and updated in the app if changed from the web app

Next step:
- Caching the list of physicians
- Caching the questionnaire
- Caching the physician questionnaire responses

**Comment by tirth-clearsense** [comment]
[commit](https://github.com/vaibhav-clearsense/personicle-react-application/commit/d11d50314600dd5facee2c2cf232cf93caa3de78) has the functionality to cache the list of physicians, questionnaire, responses and persist cached data to device async storage.

**Comment by vaibhav-clearsense** [comment]
Profile page not loading.

Response times improved for physician logging and response visualization

**Comment by vaibhav-clearsense** [comment]
Caching is implemented for events; need to implement this for data streams + Images

Images should be cached on-device and used for the next session

**Comment by tirth-clearsense** [comment]
images responses are cached. Need to show  image responses sorted by time

**Comment by vaibhav-clearsense** [comment]
Save the image (not the URL) on the device and display that to the user.
