### ISSUE TITLE
Personicle Web Dashboard: Visualize responses on user dashboard

### ISSUE THREAD

**Issue by vaibhav-clearsense** [ClearsenseData/personicle-rails#128]
Days with no data logged are missing from the charts. We need to show such days as well, these days will have empty columns in the chart

**Comment by vaibhav-clearsense** [comment]
![Image](https://user-images.githubusercontent.com/97196207/211859458-a0f12519-97ef-415c-a085-5b623433daab.png)

**Comment by tirth-clearsense** [comment]
fixed by [commit](https://github.com/tirth-clearsense/personicle-rails/commit/1736467071d691b4056444864ea0b3cd5daab4f8)
