### ISSUE TITLE
Personicle React App: Image Upload: Accept al image formats, especially the format used natively by the camera

### ISSUE THREAD

**Issue by vaibhav-clearsense** [ClearsenseData/personicle-rails#134]

**Comment by vaibhav-clearsense** [comment]
Convert all image types to JPEG on device (in react application) and handle JPEG data in the image upload API

**Comment by tirth-clearsense** [comment]
fix by [commit](https://github.com/vaibhav-clearsense/personicle-react-application/commit/16ef3e74a9b0102d62421c452a2d8bdee9736c58)
