### ISSUE TITLE
Personicle web dashboard: Image response: Allow users to delete an image

### ISSUE THREAD

**Issue by vaibhav-clearsense** [ClearsenseData/personicle-rails#137]

**Comment by vaibhav-clearsense** [comment]
Prompt the user to confirm if they want to delete an image

**Comment by tirth-clearsense** [comment]
fix by [commit](https://github.com/tirth-clearsense/personicle-rails/commit/d2179ee53aaf2dd3b7fdadfc9a8fb1f45c5440d4)
