### ISSUE TITLE
Personicle react application: Link time of upload with images

### ISSUE THREAD

**Issue by vaibhav-clearsense** [ClearsenseData/personicle-rails#142]

**Comment by vaibhav-clearsense** [comment]
Date visible in the detailed view of the image; Need to show it in the gallery as well

**Comment by tirth-clearsense** [comment]
fix by (commit)[https://github.com/vaibhav-clearsense/personicle-react-application/commit/c94e55a4e5b0a482f4c8bdf7258a9acd70b38ed2]
