### ISSUE TITLE
Personicle rails application: Signed in users should be redirected to the dashboard page directly

### ISSUE THREAD

**Issue by vaibhav-clearsense** [ClearsenseData/personicle-rails#149]

**Comment by vaibhav-clearsense** [comment]
Web dashboard showing an error, likely due to the redirect changes

**Comment by tirth-clearsense** [comment]
fixed by [commit](https://github.com/tirth-clearsense/personicle-rails/commit/b6da1fb33b8774147e2078b4aa073ff759cdeab9)
