### ISSUE TITLE
Personicle react application: Verify data caching for profile page

### ISSUE THREAD

**Issue by vaibhav-clearsense** [ClearsenseData/personicle-rails#156]

**Comment by vaibhav-clearsense** [comment]
Upon reopening the app, the loading time for the profile page seems high.
The profile page seems to be loading from web requests and not from the cache.

**Comment by tirth-clearsense** [comment]
fixed by [commit](https://github.com/vaibhav-clearsense/personicle-react-application/commit/324f2bbfae40aa130d64900488e945af6d36a7a1). User's cached  queries were being incorrectly removed when the app closes.  It is now removed when the user logs out.
