### ISSUE TITLE
Personicle web dashboard: Physician dashboard page: Page doesnt show up for new users without any questions or data

### ISSUE THREAD

**Issue by vaibhav-clearsense** [ClearsenseData/personicle-rails#159]

**Comment by tirth-clearsense** [comment]
fixed by [commit](https://github.com/tirth-clearsense/personicle-rails/commit/bfd97f1e1cf2dbc209867b477cb8cc461ad77a75)

**Comment by vaibhav-clearsense** [comment]
We were trying to loop through the list of questions for a user, which was null if the user did not have any questions attached to their profile (from the physician trying to access the data)
