### ISSUE TITLE
Deploy event consumer to read events from eventhub and store events to the database

### ISSUE THREAD

**Issue by vaibhav-clearsense** [ClearsenseData/personicle-rails#183]
The event consumer should:

1. Read the incoming events from event hub

2. Add the processed event to the database.

**Comment by vaibhav-clearsense** [comment]
Test with postman query

**Comment by tirth-clearsense** [comment]
fixed by [commit](https://github.com/vaibhav-clearsense/personicle-eventhub-consumers/commit/b4ac1606ba2cc9215853dbbd6914ba79f29f25bf)
