### ISSUE TITLE
Personicle web dashboard: Don't show logging page if food search does not give any result

### ISSUE THREAD

**Issue by vaibhav-clearsense** [ClearsenseData/personicle-rails#184]
![Image](https://user-images.githubusercontent.com/97196207/216884299-76cb9fdd-7ad2-44ae-95b8-0d3eeeb2bfb1.png)

**Comment by tirth-clearsense** [comment]
fixed by [commit](https://github.com/tirth-clearsense/personicle-rails/commit/6f50d0cfc07c3c801fe1b3c2bd7403aa78fd5384)
