### ISSUE TITLE
Personicle react application: React application timeline visualization not showing correct durations

### ISSUE THREAD

**Issue by vaibhav-clearsense** [ClearsenseData/personicle-rails#187]
React App:

![Image](https://user-images.githubusercontent.com/97196207/216918101-43d6877d-9ab5-46db-b7b4-5f9e23550749.png)

Rails Dashboard:

![Image](https://user-images.githubusercontent.com/97196207/216918174-4a6d8a60-85f9-4feb-9087-16075473a646.png)

**Comment by tirth-clearsense** [comment]
review [commit](https://github.com/vaibhav-clearsense/personicle-react-application/commit/c03684c932377134fca51ca20c68d49f2666e14a)
