### ISSUE TITLE
BUG: Personicle Web Dashboard: Weekly view for numeric survey responses

### ISSUE THREAD

**Issue by vaibhav-clearsense** [ClearsenseData/personicle-rails#199]
![Image](https://user-images.githubusercontent.com/97196207/221899330-1738e12c-2c5c-43ad-a9c7-443f18947efd.png)

The bar chart should show the average value for the week, currently, it shows the count of responses for the week

**Comment by tirth-clearsense** [comment]
fixed by [commit](https://github.com/tirth-clearsense/personicle-rails/commit/e9348ecb7226bc0afe4b9dd69010284b9d8a8617)
