### ISSUE TITLE
Bug: Personicle web dashboard: error while opening physician dashboard

### ISSUE THREAD

**Issue by vaibhav-clearsense** [ClearsenseData/personicle-rails#200]
Physician dashboard gives an error when a physician has only one patient, and the patient has no data.

**Comment by tirth-clearsense** [comment]
fixed by [commit](https://github.com/tirth-clearsense/personicle-rails/commit/ed7c8a48e8b2f9e2ada10a1e29c6a0f20cf4af9b)
